{"uuid": "7b3a42f9-a567-4e16-8b1f-6a178dc6b733", "children": ["c510b5b4-613d-4da7-af77-cd5d51a39e70"], "befores": [{"name": "_xunit_setup_method_fixture_TestXx", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102a233d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/_pytest/python.py\", line 893, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/_pytest/python.py\", line 776, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/yufei/PycharmProjects/pythonProject/test_xx.py\", line 15, in setup_method\n    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 270, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 363, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 426, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 344, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 366, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/urllib3/request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/urllib3/request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/Users/yufei/Code/pyTest/lib/python3.10/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1662371662970, "stop": 1662371662976}], "start": 1662371662970, "stop": 1662371663080}